### PR TITLE
Histogram diff

### LINKED ISSUE #59: Implement histogram algorithm for diff
**Problems**
The `diff` utility calculates and displays the differences between two files, and is typically used to investigate the changes between two versions of the same file. Git offers four `diff` algorithms, namely, _Myers_, _Minimal_, _Patience_, and _Histogram_. Without an identifying algorithm, _Myers_ is used as the default algorithm. 
In textual differencing, all `diff` algorithms are computationally correct in generating the `diff` outputs. However, the `diff` outputs are sometimes different due to different `diff` algorithms. Different `diff` algorithms might identify different change hunks, that is, a list of program statements deleted or added contiguously, separated by at least one line of unchanged context. We expect that a set of changing operations done by developers can be represented by change hunks. However, there can be inappropriate identifications of change hunks.

**Recommendation**
Based on this paper, the authors investigated the impact of adopting different `diff` algorithms (_Myers_ and _Histogram_) on empirical studies and investigated which `diff` algorithm can provide better `diff` results that can be expected to recover the changing operations [[1]](https://doi.org/10.1007/s10664-019-09772-z). 
On the impact on code churn metrics and bug-introducing change identification in 24 Java projects, the result shows different code changes based on different `diff` algorithms. For patch application, the _Histogram_ is more suitable than _Myers_ for providing the changes of code.
Therefore, we recommend using the _Histogram_ algorithm in this tool for extracting code changes.

**References**
[1] Nugroho, Y. S., Hata, H. Matsumoto, K., How different are different diff algorithms in Git?, Empirical Software Engineering (2019). [Available online](https://doi.org/10.1007/s10664-019-09772-z)

### PR DESCRIPTION
**Pull request by ishepard**
Fix #59.

Now through a setting in RepositoryMining, one can choose to use `git diff --histogram` instead of the normal `git diff`.

### CODE REVIEW

**Comment by mauricioaniche** [comment]
Maybe I am misreading something, but I think you don't really need the `diff_options` thingy in the `Commit` class. Given that the user defines this option via RepositoryMining's constructor, as a consumer of API, s/he can then _expect_ the diff to follow the histogram format.

Or does pydriller need this boolean in the Commit class for some reason?

**Comment by ishepard** [comment]
Mmmm I am not following you. I use `git diff` in the Commit class, so I need to propagate this info to the class.
How should I say to the Commit class that it has to use `git diff --histogram` instead of the normal `git diff`?

**Comment by mauricioaniche** [comment]
I see, Commit calls the diff method that exists in pygit’s commit object. Yeah, from a design perspective, it’s a bit ugly to have a configuration property as part of the commit object. And in all the instances, so even wasting some memory. 

Solving this, by means of eg a new config class, would require extra coding, and extra complexity. :/

**Comment by ishepard** [comment]
Ah I see what you mean. Yeah that might be a better choice! I coded this PR this morning and it was the easiest way to do it. Considering that I also have another issue opened which is gonna be solved similarly.
Though you are right, maybe having a config class with all the configuration there could be better! If you want, Pydriller is always opened for PRs 😛

**Pull request merged**
