### PR TITLE
Use git hyper-blame, if available, to improve SZZ results

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by marco-c** [comment]
Getting tests to pass on Travis and Appveyor is proving a pain :P

**Comment by marco-c** [comment]
Ah, the issue is simply that depot_tools still requires Python 2... I didn't notice that.
If we want to test this on Travis, we need to install Python 2 too just for depot_tools, and keep testing with Python3.

**Comment by ishepard** [comment]
I am gonna have a look at it tomorrow morning, let’s see if I can help somehow 😁

**Comment by marco-c** [comment]
> I am gonna have a look at it tomorrow morning, let’s see if I can help somehow grin

Thanks, I'm too tired to try again today ;)

I think the solution is "simply" to install Python 2 alongside Python 3, keep running tests with Python 3 but run depot_tools with Python 2. The current code is trying to do that by installing python 2 with apt-get and creating a symlink so that `python` -> `python2`, but Travis is hanging when running `python --version`.

**Comment by ishepard** [comment]
@marco-c, can you grant me access to your fork repository? So I can commit directly in the PR as well

**Comment by marco-c** [comment]
Done!

**Comment by ishepard** [comment]
So, this approach doesn't work if the user uses `virtualenv`, like in my case. So, what I am doing now, is taking the high road: I took the hyper-blame command of chromium and I am making it compatible for python3. 
The disadvantage is that we will create a new file inside Pydriller just for this command, and I will have to learn how it works (kind of at least). 
The advantage is that once it works, it will work for tests, production and everything.

**Comment by marco-c** [comment]
>  The disadvantage is that we will create a new file inside Pydriller just for this command, and I will have to learn how it works (kind of at least).

The other disadvantage is that we need to sync them (in case they fix an issue, we need to cherry-pick the fix too). It doesn't seem to be updated so often though, so maybe it won't be a big issue.

I had another idea that we could try to force the script to run with Python 2.
After cloning the repo, replace `#!/usr/bin/env python` with `#!/usr/bin/env python2` in the `git_hyper_blame.py`.

**Comment by ishepard** [comment]
Good catch. My solution of "creating" hyper-blame from scratch is not impossible, but for sure requires a lot of time and it's gonna be error-prone at the beginning. I am gonna insert it in my TODO list though! 

Right now, we can apply your suggestion and it will work 👍

**Comment by marco-c** [comment]
It worked with Python 3.7 and 3.6, that's a start ;)

**Comment by marco-c** [comment]
The issue on 3.5 and 3.4 is much easier to solve, I just need to use tmpdir_factory instead of tmp_path_factory, as the latter is not available.

**Comment by marco-c** [comment]
Finally green!

**Comment by ishepard** [comment]
Yessss! thanks @marco-c !

**Pull request merged**
