### PR TITLE
Use git built-in feature to ignore specific commits for blaming and make use of unblamable information

### LINKED ISSUE #70: Use --ignore-revs-file instead of hyper-blame
It looks like "hyper blame" is now included in git itself (see https://stackoverflow.com/a/57129540/5769903 for details).

It might be beneficial to switch to this instead of having a custom implementation. It also has some additional features, e.g. "unblamable" lines.

### PR DESCRIPTION
**Pull request by marco-c**
Fixes #70

I know I'll need to rebase.

### CODE REVIEW

**Comment by marco-c** [comment]
> I know I'll need to rebase.

Rebased, it was a quick one :)

**Comment by ishepard** [comment]
Thank you Marco for this! Everything looks good!

**Comment by marco-c** [comment]
Thanks @ishepard! Would you mind releasing a new version when you have some time?

**Comment by ishepard** [comment]
Hi @marco-c!
Yes of course. I need to do one thing first though: put a requirement in the function to check if `git` is version `2.24.x` at least. 
The tests are failing on my machine because I didn't update git. 
Now that I updated it, it works from the terminal, not from Pycharm because it's still using the old git for some reason.

**Comment by ishepard** [comment]
Released 1.10.1 😄 Merry Christmas and see you next year!

**Comment by marco-c** [comment]
> Yes of course. I need to do one thing first though: put a requirement in the function to check if git is version 2.24.x at least.

Good idea!

> Released 1.10.1 :smile:  Merry Christmas and see you next year!

Thanks! And merry Christmas to you too :christmas_tree:

**Pull request merged**
