### PR TITLE
enhance method _get_repo_name_from_url to handle case when .git is part of the repo name

### PR DESCRIPTION
**Pull request by hatrg**
Related issue #236

### CODE REVIEW

**Comment by ishepard** [comment]
Can you add a couple of tests for this function? I think there are already some tests written, you can simply add a couple of new ones with `git` in the middle.

**Comment by hatrg** [comment]
hmm, not sure why the check on windows-latest is failed yet

**Comment by hatrg** [comment]
ok now it's passed 🤯

**Comment by ishepard** [comment]
Yeah not your fault, windows is a bit flaky 😄 thanks for the PR!!!

**Pull request merged**
